In [1]:
import numpy as np, scipy as sp,pandas as pd, matplotlib.pyplot as plt
import matplotlib, sklearn
import os,sys,csv

## Data IO

In [2]:
trainPath= '../data/train.csv'
testPath= '../test.csv'

In [3]:
def csv_nrows(fpath):
    count = 0
    with open(fpath, "r") as csvfile:
        reader = csv.reader(csvfile)
        reader.next()
        '''
        for line in reader:
            count += 1
        '''
        count = sum(1 for row in reader)
    return count

In [4]:
def csv_split(fpath, nrows=5000000):
    count = csv_nrows(fpath)
    fname, ext = os.path.splitext(fpath)
    with open(fpath, "r") as csvfile:
        reader = csv.reader(csvfile)
        header = reader.next()
        
        count = 0
        for line in reader:
            if count% nrows == 0:
                print "New Patch", int(count//nrows)
                dpath = fname + '_' + str(count//nrows) + ext
                writer = csv.writer(open(dpath, 'wb'))
                writer.writerow(header)
            writer.writerow(line)
            count += 1


    print count
    print 'Done'

In [ ]:
csv_split(trainPath)

In [ ]:
print csv_nrows(trainPath)

In [ ]:

train_data = pd.read_csv(trainPath)
test_data = pd.read_csv(testPath)

## Feature Processing

In [5]:
headers = ['date_time', 
           'site_name',
           'posa_continent',
           'user_location_country',
           'user_location_region',
           'user_location_city',
           'orig_destination_distance',
           'user_id',
           'is_mobile',
           'is_package',
           'channel',
           'srch_ci',
           'srch_co',
           'srch_adults_cnt',
           'srch_children_cnt',
           'srch_rm_cnt',
           'srch_destination_id',
           'srch_destination_type_id',
           'hotel_continent',
           'hotel_country',
           'hotel_market',
           'is_booking',
           'cnt',
           'hotel_cluster']

new_fields = ['in_days', 'in_date']
modified = ['date_time']

updated = ['date_time',
           'in_date',
           'in_days',
           'site_name',
           'posa_continent',
           'user_location_country',
           'user_location_region',
           'user_location_city',
           'hotel_continent',
           'hotel_country',
           'hotel_market',
           'srch_destination_id',
           'orig_destination_distance',
           'user_id',
           'is_mobile',
           'is_package',
           'channel',
           'srch_adults_cnt',
           'srch_children_cnt',
           'srch_rm_cnt',
           'srch_destination_type_id',
           'is_booking',
           'cnt',
           'hotel_cluster']

In [6]:
sample = pd.read_csv('../data/train_0.csv')

In [7]:
def time_feature_processing(df):
    def time_interval(row):
        if pd.isnull(row['srch_ci']) or pd.isnull(row['srch_co']):
            return 1
        st = pd.Period(row['srch_ci'],freq='D')
        et = pd.Period(row['srch_co'],freq='D') 
        return et-st
    
    def time_midpoint(row):
        if pd.isnull(row['srch_ci']) or pd.isnull(row['srch_co']):
            return 0
        st = pd.Period(row['srch_ci'],freq='D')
        et = pd.Period(row['srch_co'],freq='D') 

        date = st + (et - st) / 2
        return  date.dayofyear - 1
    
    def time_dayofyear(row):
        if pd.isnull(row['date_time']):
            return 0
        tstamp = pd.to_datetime(row['date_time'])
        #print tstamp
        return tstamp.dayofyear - 1 + tstamp.hour / 24.
    
    
    df['in_days'] = df.apply(time_interval, axis= 1)
    df['in_date'] = df.apply(time_midpoint, axis= 1)
    df['date_time'] = df.apply(time_dayofyear, axis = 1)
    df.drop('srch_ci', axis=1, inplace=True)
    df.drop('srch_co', axis=1, inplace=True)

In [8]:
def nan_feature_processing(df, colname):
    med = df[colname].median()
    df[colname] = df[colname].fillna(med)

In [9]:
part_df = sample[:50000]
time_feature_processing(part_df)
nan_feature_processing(part_df,'orig_destination_distance')
#part_df[updated]

/home/nianzu/miniconda2/envs/work/lib/python2.7/site-packages/ipykernel/__main__.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/nianzu/miniconda2/envs/work/lib/python2.7/site-packages/ipykernel/__main__.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/nianzu/miniconda2/envs/work/lib/python2.7/site-packages/ipykernel/__main__.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/nianzu/miniconda2/envs/work/lib/python2.7/site-packages/ipykernel/__main__.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/nianzu/miniconda2/envs/work/lib/python2.7/site-packages/ipykernel/__main__.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/nianzu/miniconda2/envs/work/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,srch_destination_id,srch_destination_type_id,is_booking,cnt,hotel_continent,hotel_country,hotel_market,hotel_cluster,in_days,in_date
0,222.291667,2,3,66,348,48862,2234.26410,12,0,1,...,8250,1,0,3,2,50,628,1,4,240
1,222.333333,2,3,66,348,48862,2234.26410,12,0,1,...,8250,1,1,1,2,50,628,1,4,242
2,222.333333,2,3,66,348,48862,2234.26410,12,0,0,...,8250,1,0,1,2,50,628,1,4,242
3,220.750000,2,3,66,442,35390,913.19320,93,0,0,...,14984,1,0,1,2,50,1457,80,5,328
4,220.750000,2,3,66,442,35390,913.62590,93,0,0,...,14984,1,0,1,2,50,1457,21,5,328
5,220.750000,2,3,66,442,35390,911.51420,93,0,0,...,14984,1,0,1,2,50,1457,92,5,328
6,196.375000,2,3,66,189,10067,1105.37005,501,0,0,...,8267,1,0,2,2,50,675,41,1,212
7,196.375000,2,3,66,189,10067,1105.37005,501,0,1,...,8267,1,0,1,2,50,675,41,1,212
8,196.375000,2,3,66,189,10067,1105.37005,501,0,0,...,8267,1,0,1,2,50,675,69,1,212
9,196.375000,2,3,66,189,10067,1105.37005,501,0,0,...,8267,1,0,1,2,50,675,70,1,212
10,196.416667,2,3,66,189,10067,1105.37005,501,0,0,...,8267,1,0,1,2,50,675,98,1,212
11,196.416667,2,3,66,189,10067,1105.37005,501,0,0,...,8267,1,0,1,2,50,675,10,1,212
12,16.250000,2,3,66,318,22418,420.66420,756,0,1,...,8291,1,0,5,2,50,191,18,3,107
13,17.583333,2,3,66,318,52078,1105.37005,756,0,1,...,8291,1,0,1,2,50,191,28,3,106
14,20.250000,2,3,66,318,22418,421.85510,756,0,1,...,8291,1,0,1,2,50,191,25,3,107
15,20.250000,2,3,66,318,22418,421.85510,756,0,1,...,8291,1,0,1,2,50,191,25,2,108
16,21.250000,2,3,66,318,22418,421.85510,756,0,1,...,8291,1,0,1,2,50,191,25,2,108
17,23.458333,2,3,66,318,22418,421.85510,756,0,1,...,8291,1,0,1,2,50,191,25,2,107
18,23.708333,2,3,66,318,52078,1105.37005,756,0,1,...,8291,1,0,1,2,50,191,25,2,107
19,57.708333,2,3,66,318,52078,1105.37005,756,0,1,...,8291,1,0,1,2,50,191,2,2,107
20,57.750000,2,3,66,318,52078,1105.37005,756,0,1,...,8291,1,1,1,2,50,191,2,2,108
21,363.375000,2,3,66,318,21655,1105.37005,756,0,1,...,12193,6,0,2,2,50,406,16,2,37
22,363.375000,2,3,66,318,21655,1105.37005,756,0,1,...,12193,6,0,2,2,50,406,16,2,37
23,363.375000,2,3,66,318,21655,1105.37005,756,0,1,...,12193,6,0,1,2,50,406,94,2,37
24,294.500000,2,3,66,318,52997,47.70270,776,0,0,...,27082,6,0,2,2,50,641,77,1,297
25,313.500000,2,3,66,318,48382,1753.26170,776,0,1,...,8250,1,0,1,2,50,628,24,2,22
26,165.625000,30,4,195,548,56440,1105.37005,1048,0,1,...,1385,1,0,1,0,185,185,58,8,253
27,165.625000,30,4,195,548,56440,1105.37005,1048,0,1,...,1385,1,1,1,0,185,185,58,8,252
28,325.583333,30,4,195,991,47725,1105.37005,1048,0,0,...,8803,1,0,1,3,151,69,36,2,177
29,325.583333,30,4,195,991,47725,1105.37005,1048,0,0,...,8803,1,0,1,3,151,69,82,2,177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,312.583333,2,3,66,447,50736,24.16060,181701,0,0,...,11625,1,1,1,2,50,658,15,1,331
49971,312.583333,2,3,66,447,50736,24.16060,181701,0,0,...,11625,1,0,2,2,50,658,15,1,331
49972,159.875000,2,3,66,447,50736,572.95490,181701,0,0,...,12175,6,0,1,2,50,366,10,3,282
49973,159.875000,2,3,66,447,50736,572.95490,181701,0,0,...,12175,6,1,1,2,50,366,10,3,282
49974,289.833333,2,3,66,447,33335,22.03380,181701,0,0,...,11625,1,0,3,2,50,658,25,1,330
49975,289.833333,2,3,66,447,33335,22.03380,181701,0,0,...,11625,1,0,1,2,50,658,25,1,330
49976,289.833333,2,3,66,447,33335,22.03380,181701,0,0,...,11625,1,1,1,2,50,658,25,1,330
49977,309.833333,2,3,66,447,33335,7.41230,181701,0,0,...,12843,5,0,2,2,50,661,9,1,324
49978,309.833333,2,3,66,447,33335,7.40520,181701,0,0,...,12843,5,0,1,2,50,661,9,1,324
49979,309.833333,2,3,66,447,33335,7.40520,181701,0,0,...,12843,5,1,1,2,50,661,9,1,324
49980,353.833333,2,3,66,447,902,583.65150,181701,0,0,...,12175,6,0,2,2,50,366,17,4,15
49981,52.708333,2,3,66,174,30055,2257.79600,181983,0,1,...,8791,1,0,1,4,8,110,89,4,102
49982,52.708333,2,3,66,174,30055,2259.39590,181983,0,1,...,8791,1,0,1,4,8,110,52,4,102
49983,52.708333,2,3,66,174,30055,2258.48650,181983,0,1,...,8791,1,0,1,4,8,110,65,4,102
49984,52.708333,2,3,66,174,30055,2259.03740,181983,0,1,...,8791,1,0,1,4,8,110,87,4,102
49985,52.708333,2,3,66,174,30055,2255.83240,181983,0,1,...,8791,1,0,1,4,8,110,65,4,102
49986,52.708333,2,3,66,174,30055,2257.82990,181983,0,1,...,8791,1,0,1,4,8,110,66,4,102
49987,52.708333,2,3,66,174,30055,2258.17380,181983,0,1,...,8791,1,0,1,4,8,110,52,4,102
49988,57.625000,2,3,66,174,30055,2253.96840,181983,0,1,...,8791,1,0,1,4,8,110,69,4,88
49989,57.625000,2,3,66,174,30055,2259.54280,181983,0,1,...,8791,1,0,1,4,8,110,0,4,88
49990,57.625000,2,3,66,174,30055,2254.67900,181983,0,1,...,8791,1,0,1,4,8,110,65,4,88
49991,57.666667,2,3,66,174,30055,2258.10790,181983,0,1,...,8791,1,0,1,4,8,110,84,6,90
49992,66.666667,2,3,66,174,30055,2255.13840,181983,0,1,...,8791,1,0,1,4,8,110,52,7,89
49993,66.666667,2,3,66,174,30055,2250.06500,181983,0,1,...,8791,1,0,3,4,8,110,66,7,89
49994,83.708333,2,3,66,174,30055,6228.16320,181983,0,1,...,8746,1,0,2,6,105,29,95,4,277
49995,237.416667,2,3,66,174,30055,261.20320,181983,0,1,...,8250,1,0,1,2,50,628,24,2,256
49996,237.541667,2,3,66,174,30055,1745.86770,181983,0,1,...,8230,1,0,1,2,50,637,98,4,255
49997,237.541667,2,3,66,174,30055,1745.33980,181983,0,1,...,8230,1,0,1,2,50,637,41,4,255
49998,237.541667,2,3,66,174,30055,1745.91950,181983,0,1,...,8230,1,0,1,2,50,637,95,4,255
49999,237.541667,2,3,66,174,30055,1745.91950,181983,0,1,...,8230,1,0,1,2,50,637,95,3,255

## Feature Analysis

In [10]:
corr_mat = part_df[updated].corr()
plt.matshow(corr_mat)
plt.colorbar(shrink=0.5)
plt.xticks(np.arange(len(updated)),updated, rotation='vertical')
plt.yticks(np.arange(len(updated)),updated)
plt.show()

## Model

### Random Forest

In [11]:
from sklearn.datasets import load_boston
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Imputer
from sklearn.cross_validation import cross_val_score

import ml_metrics as mtr

In [12]:
X = part_df[updated[:-1]].as_matrix()
y = part_df.hotel_cluster.as_matrix()

In [24]:
def map_5_scorer(estimator, X, y):
    prob = estimator.predict_proba(X)
    def top5(row):
        return sorted(range(len(row)), key=lambda k: row[k], reverse=True)
    
    y = map(lambda x:[x], y)
    y_pred = np.apply_along_axis(top5, axis=1, arr=prob)
    return mtr.mapk(y, y_pred, 5)

In [27]:
estimator = Pipeline([("imputer", Imputer(missing_values=0,
                                          strategy="median",
                                          axis=0)),
                      ("forest", RandomForestClassifier(n_estimators=100,
                                                       n_jobs=3))])
score = cross_val_score(estimator, X, y, cv=5, scoring=map_5_scorer)
#print("Score = %.2f" % score)
print score, score.mean()

[ 0.10863878  0.12814641  0.12893877  0.11875814  0.09231426] 0.115359272599